export const REQUEST_POST_AUTH = 'REQUEST_POST_LOGIN_AUTH';
export const REQUEST_POST_AUTH_SUCCESS = 'REQUEST_POST_LOGIN_AUTH_SUCCESS';
export const REQUEST_POST_AUTH_FAIL = 'REQUEST_POST_LOGIN_AUTH_FAIL';
export const LOGGED_OUT = 'LOGGED_OUT'

export const CHANGE_AUTH_LOGIN = 'CHANGE_AUTH_LOGIN';
export const CHANGE_AUTH_PASSWORD = 'CHANGE_AUTH_PASSWORD';

export const REQUEST_GET_ALARMS_LIST = 'REQUEST_GET_ALARMS_LIST';
export const REQUEST_GET_ALARMS_LIST_SUCCESS = 'REQUEST_GET_ALARMS_LIST_SUCCESS';
export const REQUEST_GET_ALARMS_LIST_FAIL = 'REQUEST_GET_ALARMS_LIST_FAIL';

export const REQUEST_GET_ALARM = 'REQUEST_GET_ALARM';
export const REQUEST_GET_ALARM_SUCCESS = 'REQUEST_GET_ALARM_SUCCESS';
export const REQUEST_GET_ALARM_FAIL = 'REQUEST_GET_ALARM_FAIL';

export const REQUEST_GET_CARGO_LIST = 'REQUEST_GET_CARGO_LIST';
export const REQUEST_GET_CARGO_LIST_SUCCESS = 'REQUEST_GET_CARGO_LIST_SUCCESS';
export const REQUEST_GET_CARGO_LIST_FAIL = 'REQUEST_GET_CARGO_LIST_FAIL';

export const REQUEST_GET_CARRIER_LIST = 'REQUEST_GET_CARRIER_LIST';
export const REQUEST_GET_CARRIER_LIST_SUCCESS = 'REQUEST_GET_CARRIER_LIST_SUCCESS';
export const REQUEST_GET_CARRIER_LIST_FAIL = 'REQUEST_GET_CARRIER_LIST_FAIL';

export const REQUEST_GET_CAUSES_LIST = 'REQUEST_GET_CAUSES_LIST';
export const REQUEST_GET_CAUSES_LIST_SUCCESS = 'REQUEST_GET_CAUSES_LIST_SUCCESS';
export const REQUEST_GET_CAUSES_LIST_FAIL = 'REQUEST_GET_CAUSES_LIST_FAIL';

export const REQUEST_GET_REPORTS_LIST = 'REQUEST_GET_REPORTS_LIST';
export const REQUEST_GET_REPORTS_LIST_SUCCESS = 'REQUEST_GET_REPORTS_LIST_SUCCESS';
export const REQUEST_GET_REPORTS_LIST_FAIL = 'REQUEST_GET_REPORTS_LIST_FAIL';

export const REQUEST_GET_REPORT = 'REQUEST_GET_REPORT';
export const REQUEST_GET_REPORT_SUCCESS = 'REQUEST_GET_REPORT_SUCCESS';
export const REQUEST_GET_REPORT_FAIL = 'REQUEST_GET_REPORT_FAIL';

export const REQUEST_GET_TEMPLATES_PARAMS_LIST = 'REQUEST_GET_TEMPLATES_PARAMS_LIST';
export const REQUEST_GET_TEMPLATES_PARAMS_LIST_SUCCESS = 'REQUEST_GET_TEMPLATES_PARAMS_LIST_SUCCESS';
export const REQUEST_GET_TEMPLATES_PARAMS_LIST_FAIL = 'REQUEST_GET_TEMPLATES_PARAMS_LIST_FAIL';
